-- Apply to the target schema before deploying. Do not execute automatically.
ALTER TABLE MSCONV.CONVERSATION ADD COLUMN CONTEXT_JSON CLOB(16384);
CREATE TABLE MSCONV.CONVERSATION_AGENT (
 CONVERSATION_ID INTEGER NOT NULL REFERENCES MSCONV.CONVERSATION(ID),
 AGENT_ID VARCHAR(255) NOT NULL, EMAIL VARCHAR(255), NAME VARCHAR(255),
 SUBSCRIBED SMALLINT NOT NULL DEFAULT 0, LAST_READ_MESSAGE_ID INTEGER,
 UPDATED_DATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (CONVERSATION_ID, AGENT_ID)
);
-- Existing public responders are retained as participants. rcNext supplies their
-- verified email/name on their next reply; do not guess email from their user ID.
INSERT INTO MSCONV.CONVERSATION_AGENT (CONVERSATION_ID, AGENT_ID, SUBSCRIBED)
 SELECT DISTINCT CONVERSATION_ID, AUTHOR_ID, 1 FROM MSCONV.MESSAGE
 WHERE AUTHOR_TYPE = 'AGENT' AND VISIBILITY = 'PUBLIC' AND AUTHOR_ID IS NOT NULL;
-- Journal the new table using the library default journal before deployment.
-- Legacy ASSIGNEE_ID and ASSIGNEE_LAST_READ_MESSAGE_ID columns are unused.
-- Retain them during rollout; drop separately after all old binaries are retired.

CREATE INDEX MSCONV.MESSAGE_UNREAD_IDX ON MSCONV.MESSAGE (CONVERSATION_ID, AUTHOR_TYPE, VISIBILITY, ID);
